server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/lmm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      validation-query: SELECT 1
      test-on-return: false
      test-while-idle: true
      test-on-borrow: false

eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      单机版：defaultZone: http://eureka7001.com:7001/eureka/ # 入驻地址
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/erueka # 入驻地址
#显示服务别名和IP地址
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true
ribbon:
  #指的是建立连接所用时间,适用于网络状况正常情况下,两端连接所用时间
  ReadTimeout: 6000
  #指的是建立连接后从服务器读取可用资源所用时间
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atlmm.springcloud.entities


